# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_gameevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
